# Generated by Django 5.2 on 2025-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('sell', 'Do sprzedania'), ('todo', 'Do zrobienia')], default='todo', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
